fb_credentials:
  app_id: '1137111439718870'
  app_secret: '44fddc04b3e6c1f8ed869823a2f4d2cd'
  default_graph_version: 'v2.8'
gl_credentials:
  auth_uri: 'https://accounts.google.com/o/oauth2/auth'
  client_id: '10738121603-raog87nda9up9gb44ksg8drs2aj6i2ks.apps.googleusercontent.com'
  client_secret: 'U__Z-R0NhqjhzfhCVOW9_P90'
  project_id: 'fine-proxy-145818'
  token_uri: 'https://accounts.google.com/o/oauth2/token'
  auth_provider_x509_cert_url: 'https://www.googleapis.com/oauth2/v1/certs'